### PR TITLE
Add SWC test files

### LINKED ISSUE #1: Add input files from SWC

### PR DESCRIPTION
**Pull request by barrc**
Closes #1

### CODE REVIEW

**Comment by michaeltryby** [comment]
Hey @barrc, I finished upgrading the required Python packages for reg testing. I am going to push some commits to this PR to get the tests you added running. Then we can merge it. Sound good? Thanks!

**Comment by barrc** [comment]
@michaeltryby thanks, that sounds good to me!

**Comment by michaeltryby** [comment]
@barrc It turned out to be straight forward to get nrtest to manage the auxiliary data files. I just added them to the test configurations and it worked. Nice when things are that easy!

**Comment by barrc** [comment]
Great, thanks @michaeltryby!

**Pull request merged**
